name: CI/CD Pipeline

on:
  push:
      branches:
        - 'main'
        - 'develop'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - run: go build -v .
      - run: go test ./