name: CI/CD Pipeline
permissions:
  contents: read
  pull-requests: write
  
on:
  push:
      branches:
        - 'main'
        - 'develop'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.24.5
      - id: govulncheck
        uses: golang/govulncheck-action@v1
        with:
           go-version-input: 1.24.5
           go-package: ./...
      - run: go vet ./
      - run: go test ./
      - run: go build -v .


  dockerize:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/go-devops-app:latest .
      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - name: Push to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/go-devops-app:latest
      - name: Run container
        run: |
          docker pull ofausto/go-devops-app:latest
          sleep 5
          docker run -d -p 8080:8080 ofausto/go-devops-app:latest
          sleep 30
          curl -f http://localhost:8080 || exit 1